{% set name = "librdkafka" %}
{% set version = "1.5.0" %}
{% set sha256 = "f7fee59fdbf1286ec23ef0b35b2dfb41031c8727c90ced6435b8cf576f23a656" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/edenhill/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cyrus-sasl
    - libgsasl  # [not osx]
    - lz4-c
    - openssl
    - zlib
  run:
    - cyrus-sasl
    - libgsasl  # [not osx]
    - lz4-c
    - openssl
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/librdkafka${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/librdkafka++${SHLIB_EXT}  # [not win]

    - conda inspect linkages {{ name }}  # [unix]
    - conda inspect objects {{ name }}   # [osx]

about:
  home: https://github.com/edenhill/librdkafka
  license: BSD-2-clause
  license_family: BSD
  license_file: LICENSES.txt
  summary: The Apache Kafka C/C++ client library
  description: |
    librdkafka is a C library implementation of the Apache Kafka protocol,
    containing both Producer and Consumer support. It was designed with message
    delivery reliability and high performance in mind, current figures exceed 1
    million msgs/second for the producer and 3 million msgs/second for the
    consumer.
